# user params
AbundanceBoost = 1
BeeSpeciesInitialQueensList = [["B_terrestris", 500]]
COLONIES_IBM = 0
CumulVisitsOnlyLastYear::Bool = false
FlowerspeciesFile = "flowerspecies.csv" # replace in code
FoodSourceLimit = 25
ForagingMortalityFactor = 1
MortalityForager = 1.0e-5 # 1/s
# 1.0e-5 for high, 2.14e-6 for intermediate, and 2.75e-07 for low
Gridsize = 500
HabitatsFile = "habitats.csv"
KeepDeadColonies::Bool = true
Lambda_detectProb = -0.005
MapAreaIncluded = "complete" # remove
MasterSizeFactor = 1
MaxForagingRange = 10000 # m
MaxHibernatingQueens = 10000
MaxPatchRadius = 500 # m
MergeHedges::Bool = true
MinSizeFoodSources::Bool = true
N_Badgers = 0
RemoveEmptyFoodSources::Bool = true
SexLocus::Bool = false
BeespeciesFile = "beespecies.csv" # replace in code
StopExtinct::Bool = true
UnlimitedMales::Bool = true
Weather = "Constant 8 hrs" # remove

# beesteward params
AssertionViolated::Bool = false
CallItaDay = 24*60*60
CohortSymbolSize = 0.75 * MasterSizeFactor
ColonySymbolsize = 9 * MasterSizeFactor
DailySwitchProbability = 0.13
EnergyFactorOnFlower = 0.3
EnergyHoney = 22.67 # kJ/ml
EnergyRequiredForPollenAssimilation = 6.2 # kJ/g
EnergySucrose = 0.00582 # kJ/mymol
FoodsourcesInFlowerUpdate::Bool = false
FoodsourceSymbolSizeFactor = 1.5 * MasterSizeFactor
ForagingRangeMax = 758 # m
GetUpTime = 1 # s
LarvaWorkerRatioTH = 3
MaxLifespanMales = 30
MetabolicRateFlight = 488.6 # W/kg
MinFoodSourceSymbolSize = 2.5 * MasterSizeFactor
MortalityAdultsBackground_daily = 0
N_ForeignAlleles = 24
NestSearchTime_h = 6
NotSetHigh = 999999999999999
NotSetLow = -999999999999999
QueenDestinedEggsBeforeSP_d = 5
QueensProducingColoniesList = []
QueenSymbolSize = 2 * MasterSizeFactor
StepWidth = 0.5 * MasterSizeFactor
Sunrises = 8*60*60 # s
SelectedFieldsList = []
PopulationSizeDay365List = []
Survived::Bool = true